spring:
  profiles: test
  datasource:
    #url: jdbc:postgresql://localhost:5432/app
    url: jdbc:postgresql://${SPRING_KOTLIN_EXPOSED_DB_CI_HOST:localhost}:5432/app_test
    username: app_rw
    password: app_rw

app:
  envName: test
