version: '3'
services:
  spring-kotlin-exposed-db-ci:
    image: local/spring-kotlin-exposed-db:latest
    ports:
      - "5435:5432"
    networks:
      - spring-kotlin-exposed-ci-network
    tmpfs:
      - /tmp
      - /var/run/postgresql
      - /var/lib/postgresql/data
networks:
  spring-kotlin-exposed-ci-network: {}